branches:
  only:
  - master
  - /^assess-.*$/
language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  webhooks: http://api.pythonclassic.com/travisci
